# my global config
global:
  scrape_interval: 20s    # Set the scrape interval to every 20 seconds. Default is every 1 minute.
  evaluation_interval: 20s  # Evaluate rules every 20 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).